apps/web/src/app/components/logo.tsx, apps/web/src/app/components/mode-switcher.tsx, apps/web/src/app/components/site-footer.tsx, apps/web/src/app/components/site-header.tsx, apps/web/src/app/components/waitlist-form.tsx
Providing accessibility improvements as mentioned in issue #16
=> fix: a11y improvements for landing page (issue #16)

.github/workflows/trigger-tasks-deploy.yml, apps/app/src/lib/encryption.ts, apps/app/src/trigger/deel/index.ts, apps/app/src/trigger/deel/schedule.ts, apps/app/trigger.config.ts, apps/web/trigger.config.ts
- Update trigger configs to include new trigger directories
- Modify encryption method to use Node.js native scrypt instead of argon2
- Remove Deel-specific tasks and update workflow to include trigger directory
- Add SECRET_KEY to deployment workflow
- Simplify key derivation and remove external dependency
=> refactor: update Trigger.dev configuration and encryption strategy

apps/app/src/app/[locale]/(app)/(dashboard)/settings/api-keys/page.tsx
- Remove unnecessary container padding classes
- Streamline page structure for API keys section
- Maintain max-width constraint for consistent page design
=> refactor(settings): simplify API keys page layout

apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/vendors/(overview)/page.tsx
- Added i18n support by fetching translations in the Vendors overview page.
- Ensured type safety and maintained responsive design principles with Tailwind CSS.
=> feat: integrate internationalization support in vendors overview page

apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/policies/(overview)/components/policy-status-chart.tsx
- Reformatted code for better readability and consistency in the PolicyStatusChart component.
- Enhanced the layout and structure of the component while maintaining existing functionality.
- Ensured proper use of TypeScript interfaces and modularization for improved maintainability.
=> refactor: improve PolicyStatusChart component structure and readability

packages/auth/src/auth.ts, turbo.json
- Added environment variables for authentication in the turbo.json file.
- Set the AUTH_SECRET in the auth.ts file to enhance security and configuration management.
=> feat: update auth configuration and environment variables

packages/auth/src/create-auth.ts
- Removed the logic for retrieving the authentication secret from environment variables and the associated error handling for production environments.
- Simplified the fallback mechanism to use a default secret in non-production environments, enhancing code clarity and maintainability.
- Maintained type safety and modular structure in the authentication configuration.
=> refactor: streamline secret handling in create-auth.ts

packages/auth/src/create-auth.ts
- Reorganized imports in create-auth.ts for better clarity and structure, ensuring all necessary modules are included.
- Updated AuthConfig interface to require the secret and googleAuth properties, improving type safety.
- Simplified the handling of the google provider configuration by directly using the provided googleAuth object.
- Maintained modular structure and type safety throughout the authentication configuration.
=> refactor: enhance create-auth.ts imports and configuration

apps/app/src/utils/auth.ts
- Updated the authentication utility to check for both AUTH_SECRET and BETTER_AUTH_SECRET, improving flexibility in secret management.
- Simplified the secret assignment logic to prioritize BETTER_AUTH_SECRET if AUTH_SECRET is not set, ensuring robust error handling.
- Maintained type safety and modular structure throughout the authentication configuration.
=> refactor: enhance secret handling in auth utility

apps/portal/src/actions/safe-action.ts
- Updated the authActionClient to extract user and session data from the authentication response, improving context handling for subsequent actions.
- Simplified error handling for unauthorized access and ensured consistent logging in development mode.
- Commented out audit logging logic for future implementation, maintaining code clarity and modularity.
=> refactor: enhance authActionClient to include user data in context

README.md, apps/portal/.env.example
- Updated the README to include instructions for setting up the .env file for the portal.
- Added a new .env.example file for the portal with required environment variables for authentication, database, and public settings.
- Fixes #312
- Fixes COM-58
=> docs: update README and add .env.example for portal

apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/frameworks/data/getAllFrameworkInstancesWithControls.ts
- Replaced the cache wrapper with a direct async function definition for getAllFrameworkInstancesWithControls.
- Improved readability and maintainability by removing unnecessary complexity in the function structure.
- What are the minimal test …
=> refactor: simplify getAllFrameworkInstancesWithControls function

apps/app/.env.example, apps/app/sentry.edge.config.ts, turbo.json
- Updated turbo.json to include SENTRY_AUTH_TOKEN in environment variables.
- Modified .env.example to document SENTRY_AUTH_TOKEN for Sentry integration.
- Ensured Sentry configuration in sentry.edge.config.ts maintains formatting consistency.
- …
=> chore: add Sentry authentication token to configuration

apps/app/src/app/[locale]/(app)/setup/page.tsx, apps/app/src/app/[locale]/layout.tsx, apps/app/src/app/[locale]/page.tsx, apps/app/src/components/forms/create-organization-form.tsx
- Reformatted layout.tsx for consistent code style and readability.
- Updated page.tsx to ensure proper redirection logic by returning redirect calls.
- Enhanced create-organization-form.tsx with improved state management and form handling.
- Ensured consistent formatting across components for better maintainability.
- Highlight any …
=> refactor: improve layout and page redirection logic

apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/employees/all/components/table/columns.tsx, apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/frameworks/page.tsx, apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/vendors/[vendorId]/components/title-and-description/update-title-and-description-form.tsx, apps/app/src/components/data-table/data-table-filter-list.tsx, apps/app/src/components/forms/risks/risk-overview.tsx, apps/app/src/components/integrations/integrations-card.tsx, apps/app/src/components/integrations/integrations.tsx, apps/app/src/components/magic-link.tsx, apps/app/src/components/sheets/add-employee-sheet.tsx, apps/app/src/components/tables/api-keys/create-api-key-dialog.tsx, apps/app/src/components/tests/charts/tests-by-assignee.tsx, apps/app/src/hooks/use-notifications.ts, apps/portal/src/app/[locale]/(app)/(home)/components/Overview.tsx, apps/portal/src/app/[locale]/(app)/(home)/components/policy/PolicyGrid.tsx, packages/ui/src/components/combobox-dropdown.tsx, packages/ui/src/components/secondary-menu.tsx, yarn.lock
- Removed redundant console.log statements across various components to enhance code clarity and maintainability.
- Adjusted formatting for consistency in imports and component structure.
- Minor refactoring in the employee and integration components for improved readability.
- Fixes #324
- Fixes COMP-66
Open developer console and use the app; nothing should be logged to the frontend
=> refactor: clean up code and remove unnecessary console logs

apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/error.tsx, apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/frameworks/error.tsx, apps/app/src/app/[locale]/(app)/setup/error.tsx, apps/app/src/app/[locale]/error.tsx, apps/app/src/app/[locale]/not-found.tsx, apps/app/src/app/[locale]/providers.tsx, apps/app/src/app/global-error.tsx
- Introduced new error handling components for various locales, ensuring consistent user feedback across the application.
- Updated existing GlobalError component for improved formatting and clarity.
- Enhanced error logging in ErrorPage components to capture error details effectively.
- Applied consistent formatting and structure across all error handling components for maintainability.
- Add …
=> refactor: standardize error handling components

apps/app/src/app/[locale]/providers.tsx, packages/analytics/src/components/provider.tsx
=> use email for posthog

apps/app/src/app/posthog.ts
=> don't pass in host for server side ph

apps/app/src/actions/organization/create-organization-action.ts, apps/app/src/app/[locale]/error.tsx, apps/app/src/components/header.tsx, apps/app/src/components/modals/create-org-modal.tsx, apps/app/src/components/organization-switcher.tsx
- Added revalidation for organization paths and user tags after successful organization creation.
- Improved error page layout with responsive design and added support contact link.
- Updated header component to include notification center and improved structure.
- Refactored organization switcher for better organization management and UI consistency.
- Enhanced create organization modal with improved form handling and user feedback.
- Fixes #327 (GitHub issue number)
- Fixes COMP-69 (Linear issue number - should be visible at the bottom of the GitHub issue description)
=> refactor: enhance organization creation and error handling

.github/workflows/database-migrations.yml
- Adjusted directory path for Prisma migration commands to improve organization.
- Removed unnecessary database seed step from the workflow for cleaner execution.
- What is expected (happy path) to have …
=> fix: update database migration workflow for Prisma

.github/workflows/database-migrations.yml
- Adjusted the directory path for Prisma migration commands to specify the schema location explicitly.
- Improved organization of the migration workflow for better clarity and maintainability.
- What is …
=> fix: update database migration workflow for Prisma schema path

apps/app/src/actions/organization/create-organization-action.ts, apps/app/src/actions/organization/lib/utils.ts, yarn.lock
optimize write of create org function
- Fixes COMP-62 (Linear issue number - should be visible at the bottom of the GitHub issue description)
Create a new org and see if it works, how long it takes
=> Optimize create org action

apps/app/sentry.server.config.ts, apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/vendors/(overview)/components/VendorColumns.tsx, apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/vendors/(overview)/components/VendorsTable.tsx, apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/vendors/(overview)/data/queries.ts, apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/vendors/(overview)/data/validations.ts, apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/vendors/(overview)/page.tsx
Fix search on vendors table
- Fixes COMP-90 (Linear issue number - should be visible at the bottom of the GitHub issue description)
Search on the vendors table...
=> Fix search on Vendors table

apps/app/trigger.config.ts, bun.lock, packages/db/package.json, yarn.lock
- Changed the Prisma schema path in package.json to point directly to the schema directory, enhancing clarity in database configuration.
- Any …
=> chore: update Prisma schema path for improved clarity

apps/app/src/actions/organization/accept-invitation.ts, apps/app/src/actions/organization/create-organization-action.ts
- Fixes #394 (GitHub issue number)
- Fixes COMP-89 (Linear issue number - should be visible at the bottom of the GitHub issue description)
- Updated accept-invitation and create-organization-action files to include first and last names when creating contacts via the Resend API.
- Ensured names are extracted from the user object, improving contact management accuracy.
=> feat: enhance contact creation with user names in organization actions

apps/app/package.json, apps/app/src/actions/organization/accept-invitation.ts, apps/app/src/actions/organization/create-organization-action.ts, apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/risk/(overview)/components/table/RiskColumns.tsx, apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/vendors/(overview)/components/VendorColumns.tsx, apps/app/src/app/[locale]/(app)/setup/components/accept-invite.tsx, apps/app/src/app/[locale]/(app)/setup/page.tsx, apps/app/src/app/[locale]/(public)/auth/page.tsx, apps/app/src/app/global-error.tsx, apps/app/src/components/SelectAssignee.tsx, apps/app/src/components/comments.tsx, apps/app/src/components/forms/create-organization-form.tsx, apps/app/src/components/magic-link.tsx, apps/app/src/components/policies/charts/policies-by-assignee.tsx, apps/app/src/components/risks/charts/RisksAssignee.tsx, apps/app/src/components/tests/charts/tests-by-assignee.tsx, apps/app/src/components/user-menu.tsx, apps/app/src/utils/auth-client.ts, apps/app/src/utils/auth.ts, bun.lock, packages/email/emails/magic-link.tsx, packages/email/lib/magic-link.ts, yarn.lock
- Added magic link authentication with better-auth
- Integrated `react-wrap-balancer` for improved text wrapping in the application.
- Updated user identification logic across various components to fallback on email when names are not available, enhancing user experience and consistency.
- Refactored organization actions to revalidate paths for user organizations upon creation, ensuring up-to-date data rendering.
- Test authentication (make sure other providers work too)
- Test org creation
- Ensure user can create risks, vendors etc
=> feat: add magic link authentication

.github/workflows/database-migrations.yml
=> update schema path

.github/workflows/database-migrations.yml
- Modified the database-migrations.yml workflow to change the working directory for the prisma migrate deploy command, improving clarity and execution flow.
- What is expected (happy path) to have (input …
=> chore: update database migration command in workflow

packages/db/package.json, packages/db/prisma/schema/schema.prisma, packages/db/prisma/schema/shared.prisma
=> this should work?

.github/workflows/trigger-tasks-deploy.yml
=> generate before deploy

apps/app/package.json, apps/app/src/components/header.tsx
- Updated the development script in package.json to use the --turbo flag for improved performance.
- Refactored the Header component to replace FeedbackForm with a Link component for better UI consistency and maintainability.
- Fixes #361 (GitHub issue number)
- Fixes COMP-76 (Linear issue number - should be visible at the bottom of the GitHub issue description)
Click the buttons in the header
=> chore: enhance development script and refactor header component

apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/risk/(overview)/page.tsx, apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/risk/[riskId]/page.tsx, apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/vendors/[vendorId]/page.tsx, apps/app/src/components/app-onboarding.tsx, apps/app/src/components/risks/charts/RiskMatrixChart.tsx, apps/app/src/locales/onboarding/app-onboarding.ts
- Refactored AppOnboarding component for improved layout and responsiveness.
- Updated CTA text in localization files for clarity and conciseness.
- Adjusted estimated time display in the footer for accuracy.
=> feat: update onboarding component and localization strings

packages/ui/src/globals.css
=> Scroll bar

apps/app/src/actions/organization/lib/stripe.ts
- Eliminated the console warning for unconfigured Stripe environment variables (STRIPE_SECRET_KEY, STRIPE_WEBHOOK_SECRET) to streamline the initialization process.
- This change enhances the clarity of the code by focusing on the successful creation of the Stripe instance.
- Are there environment …
=> fix: remove warning for missing Stripe environment variables

apps/app/src/actions/research-vendor.ts, apps/app/src/env.mjs
- Updated env.mjs to include FIRECRAWL_API_KEY as an optional environment variable.
- Refactored researchVendorAction to utilize the FIRECRAWL_API_KEY from the environment configuration instead of process.env, enhancing consistency and maintainability.
=> feat: add FIRECRAWL_API_KEY support in environment configuration

apps/app/src/actions/organization/remove-member.ts, apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/settings/members/components/InviteMemberForm.tsx, apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/settings/members/components/MembersList.tsx, apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/settings/members/components/invalidateMembers.ts, apps/app/src/app/[locale]/(app)/setup/components/accept-invite.tsx, yarn.lock
=> fix invites

apps/app/src/app/[locale]/(app)/setup/components/accept-invite.tsx, apps/app/src/app/[locale]/(app)/setup/page.tsx, apps/app/src/app/[locale]/(public)/auth/page.tsx, apps/app/src/app/[locale]/(public)/layout.tsx
=> fix invite when already have existing org

apps/app/src/actions/change-organization.ts, apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/layout.tsx, apps/app/src/components/main-menu.tsx, apps/app/src/components/organization-switcher.tsx, apps/app/src/components/sidebar-logo.tsx, apps/app/src/components/sidebar.tsx
=> fix org switching

.cursor/rules/react-code.mdc, apps/app/src/app/[locale]/(internal)/internal/admin/actions.ts, apps/app/src/app/[locale]/(internal)/internal/admin/members-modal.tsx, apps/app/src/app/[locale]/(internal)/internal/admin/organization-dashboard.tsx, apps/app/src/app/[locale]/(internal)/internal/admin/organization-list.tsx, apps/app/src/app/[locale]/(internal)/internal/admin/page.tsx, apps/app/src/utils/auth.ts
=> Add admin dashboard with organization management and member controls

apps/app/src/app/[locale]/providers.tsx, apps/app/src/components/forms/create-organization-form.tsx
- Added Google Tag Manager to the Providers component for user tracking.
- Implemented GTM event sending on successful organization creation in the OnboardingClient component.
=> feat: integrate Google Tag Manager for enhanced tracking

apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/controls/loading.tsx, apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/employees/(overview)/loading.tsx, apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/evidence/loading.tsx, apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/implementation/loading.tsx, apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/integrations/loading.tsx, apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/integrations/page.tsx
- Implemented loading components for controls, employees, evidence, implementation, and integrations pages.
- Each loading component utilizes Suspense with a fallback skeleton UI for improved user experience during data fetching.
=> feat: add loading components for various dashboard sections

.github/workflows/database-migrations-dev.yml
=> Add GitHub workflow to run database migrations on dev branch

packages/ui/src/components/button.tsx
- Adjusted class names in the button component for better alignment and spacing.
- Ensured consistent handling of whitespace and SVG pointer events for enhanced usability.
- What is expected (happy path) …
=> fix: refine button component styles for improved layout

.github/workflows/database-migrations-dev.yml, .github/workflows/database-migrations.yml, .github/workflows/trigger-tasks-deploy-dev.yml, .github/workflows/trigger-tasks-deploy.yml
- Updated `database-migrations-dev.yml` to trigger on `main` branch instead of `dev`.
- Modified `database-migrations.yml` to trigger on `release` branch instead of `main`.
- Changed `trigger-tasks-deploy-dev.yml` to trigger on `main` branch instead of `dev`.
- Adjusted `trigger-tasks-deploy.yml` to trigger on `release` branch instead of `main`.
- Add side-by-side screenshots of the original and updated …
=> chore: update GitHub workflows to change branch triggers

apps/app/src/middleware.ts
refactor: simplify middleware by removing session handling and unused variables
- Removed session cookie handling and related logic from the middleware.
- Cleaned up unused variables and streamlined the middleware function for improved clarity and performance.
=> remove middleware

apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/implementation/actions.ts, apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/implementation/types.ts, apps/app/src/components/onboarding/FloatingOnboardingChecklist.tsx
- Added markOnboardingStep action to update onboarding step completion status.
- Implemented optimistic UI updates in FloatingOnboardingChecklist for a smoother user experience.
- Integrated error handling and state management for onboarding step updates.
- Updated types to ensure type safety for onboarding steps and checklist items.
- …
=> feat: enhance onboarding actions and checklist component

apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/implementation/components/ChecklistItem.tsx
- Removed unused Badge import and consolidated imports for better readability.
- Updated ChecklistItemProps import path for consistency with project structure.
- Enhanced code organization by removing unnecessary components and ensuring clarity in the ChecklistItem implementation.
- Are there …
=> refactor: streamline ChecklistItem component and update imports

apps/app/src/app/[locale]/page.tsx, apps/app/src/middleware.ts
=> Add auth redirect logic and clean up middleware path handling

apps/trust/src/app/[id]/components/compliance-header.tsx
(same as title)
Before:
After:
Open trust hub in small screen and see the button. With this PR, the button will not overflow.
=> Fix button overflow in trust hub in small screen 

apps/app/src/app/[locale]/(app)/(dashboard)/[orgId]/policies/[policyId]/data/index.ts
=> chore: dont return early

apps/app/src/components/animated-layout.tsx
- adjust layout containers so sidebar scrolls independently
- `bun run lint` *(fails: turbo: command not found)*
=> Fix animated layout scrolling

apps/app/src/app/(app)/(dashboard)/[orgId]/layout.tsx, apps/app/src/components/organization-switcher.tsx, apps/app/src/middleware.ts
=> fix: fix issue with redirect to onboarding

apps/app/src/app/api/retool/reset-org/route.ts
- import initializeOrganization function
- call initializeOrganization after resetting organization data
- provide frameworkIds and organizationId for initialization
- What is expected (happy path) to have …
=> feat(api): add organization initialization after reset

README.md
The logo link was broken and it was speaking about waitlist.
Done
=> Fix: REAMDE

apps/app/customPrismaExtension.ts
- Added informative echo statements to the Prisma client generation command for better visibility during execution.
- Implemented checks for the existence of the generated Prisma client directory and added commands to copy the generated client to the standard location.
- Included final checks for query engines in both the generated and client directories to ensure successful generation.
- Add …
=> feat: enhance Prisma client generation process with detailed logging

apps/app/src/app/layout.tsx
- Added 'force-dynamic' export to enable dynamic rendering in the layout component.
- Set revalidation to 0 to ensure fresh data on every request.
- What is expected (happy path) to have (input and …
=> feat: enable dynamic rendering and set revalidation for layout component

apps/portal/src/app/api/download-agent/scripts/windows.ts
- Improved the logic for selecting and creating primary and fallback directories, adding detailed logging for success and failure scenarios.
- Updated marker file writing commands to include explicit logging messages, enhancing clarity during execution.
- Removed outdated registry writing logic as per request, streamlining the script's functionality.
- Add side-by-side screenshots of the original and …
=> fix: enhance directory and marker file handling in Windows script

apps/portal/src/app/api/download-agent/scripts/windows.ts
- Added structured comments to improve readability and organization of the script.
- Enhanced logging messages for better clarity during execution, particularly for directory selection and permission settings.
- Improved error handling and messaging for missing marker files, ensuring clearer feedback on script status.
- Highlight any …
=> fix: enhance structure and logging in Windows script

apps/portal/src/app/api/download-agent/scripts/windows.ts
- Removed redundant echo statements to improve script clarity and reduce clutter in the output.
- Introduced a main subroutine to organize script flow and enhance readability.
- Added structured comments to delineate sections of the script, improving maintainability and understanding of the code.
- …
=> fix: streamline script structure and enhance logging in Windows script

apps/app/src/jobs/tasks/device/create-fleet-label-for-org.ts
- Updated directory paths to use double backslashes for proper formatting in Windows.
- Ensured consistency in path definitions to prevent potential parsing issues during execution.
- What is expected …
=> fix: correct Windows path formatting in fleet label creation script

apps/app/src/app/(app)/[orgId]/people/[employeeId]/components/EmployeeTasks.tsx, apps/app/src/app/(app)/[orgId]/people/devices/components/HostDetails.tsx, apps/app/src/components/status-indicator.tsx, apps/portal/src/app/(app)/(home)/[orgId]/policy/[policyId]/page.tsx, packages/ui/src/components/editor/index.tsx
- Updated various components to use 'text-primary' for status indicators and icons, enhancing visual consistency.
- Adjusted border colors in HostDetails and EmployeeTasks components to align with the new color scheme.
- Simplified background styles in PolicyPage and status-indicator for a more cohesive design.
=> refactor: standardize color usage across components

apps/api/src/app.module.ts, apps/api/src/devices/devices.controller.ts, apps/api/src/devices/devices.module.ts, apps/api/src/devices/devices.service.ts, apps/api/src/devices/dto/device-responses.dto.ts, apps/api/src/devices/dto/devices-by-member-response.dto.ts, apps/api/src/devices/dto/member-responses.dto.ts, apps/api/src/lib/fleet.service.ts, apps/app/src/utils/auth.ts, apps/portal/src/app/lib/auth.ts
=> Production Release
